{
 "title": "Data Layer",
 "description": "metrics for the data layer",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(atomix_role,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"},partion)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tasklist Importer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import latencies, 10 min average, sec",
     "type": "timeseries",
     "description": "The time needed for the importer to read documents from the zeebe records index for a single import batch.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(tasklist_import_query_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])/rate(tasklist_import_query_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])>0)",
       "legendFormat": "Importer read latency"
      },
      {
       "expr": "avg(rate(tasklist_import_index_query_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])/rate(tasklist_import_index_query_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])>0)",
       "legendFormat": "Importer index latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Tasklist Archiver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Operate Importer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput Exported and Imported records (avg)",
     "type": "timeseries",
     "description": "Throughput of documents processed and imported.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 753 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(operate_events_processed_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (status)",
       "legendFormat": "imported"
      },
      {
       "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\", action=~\"exported\",partition=~\"$partition\", valueType!~\"MESSAGE_SUBSCRIPTION|MESSAGE|JOB_BATCH\"}[$__rate_interval]))",
       "legendFormat": "exported"
      }
     ]
    },
    {
     "title": "Latency (avg)",
     "type": "timeseries",
     "description": "Shows the time (latency) between writing the command to the dispatcher, processing, exporting, and then importing the record.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 760 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_time_seconds_sum{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval])) / sum(rate(operate_import_time_seconds_count{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Import latency"
      },
      {
       "expr": "sum(rate(zeebe_stream_processor_latency_sum{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval]) or rate(zeebe_stream_processor_latency_seconds_sum{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) / sum(rate(zeebe_stream_processor_latency_count{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval]) or rate(zeebe_stream_processor_latency_seconds_count{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "Processing latency"
      },
      {
       "expr": "sum(rate(zeebe_exporting_latency_sum{namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) / sum(rate(zeebe_exporting_latency_count{namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "Exporting latency"
      }
     ]
    },
    {
     "title": "Importing: read duration",
     "type": "timeseries",
     "description": "The time it takes for the importer to read an record on average from ES",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_query_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])) by (type) / sum(rate(operate_import_query_seconds_count{namespace=\"$namespace\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Import processing duration (AVG)",
     "type": "timeseries",
     "description": "Time the import writer thread needs on average to process an ImportBatch (containing several Zeebe records).",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_processing_duration_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])) by (type) / sum(rate(operate_import_processing_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Importing: write duration (avg)",
     "type": "timeseries",
     "description": "The time it takes to write the bulk requests (during importing) to ES on average.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_index_query_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])) by (type) / sum(rate(operate_import_index_query_seconds_count{namespace=\"$namespace\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Import queue size",
     "type": "timeseries",
     "description": "There is a queue of import jobs where each job has to import a batch of records. This details how many such jobs are currently in the queue.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 773 },
     "targets": [
      {
       "expr": "sum(operate_import_queue_size{namespace=~\"$namespace\", pod=~\"$pod\"} ) by (type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Operate Archiver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  },
  {
   "title": "Camunda Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Camunda Exporter (Flush Duration)",
     "type": "heatmap",
     "description": "Each time a non empty bulk request if flushed, this is how long the flush takes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Failure Rate)",
     "type": "gauge",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(zeebe_camunda_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_camunda_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Failure Type)",
     "type": "timeseries",
     "description": "When bulk request flushes fail, the type of error returned is counted.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "increase(zeebe_camunda_exporter_flush_failure_type_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Time since last flush)",
     "type": "timeseries",
     "description": "The time in seconds since the last flush.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "min by (partition) (zeebe_camunda_exporter_since_last_flush_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "partition-{{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Records to export backlog)",
     "type": "timeseries",
     "description": "How far behind each exporter is from exporting the records which have been committed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "max (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) by (partition) - max (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", exporter=~\"(?i)camundaexporter\"}) by (partition)",
       "legendFormat": "partition {{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Bulk Size)",
     "type": "timeseries",
     "description": "For every non empty flush of a bulk request, this is the number of entities flushed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_bulk_size_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition) / \nsum(increase(zeebe_camunda_exporter_bulk_size_count{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "partition-{{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Latency)",
     "type": "timeseries",
     "description": "How long an export request is open and collecting new records before flushing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "min by (partition) (\n  rate(zeebe_camunda_exporter_flush_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval]) / \n  rate(zeebe_camunda_exporter_flush_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval])\n)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Process cache eviction",
     "type": "timeseries",
     "description": "Shows the rate of evictions of the process cache",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_evictions_total{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Evictions {{partition}}"
      }
     ]
    },
    {
     "title": "Process cache access",
     "type": "timeseries",
     "description": "Shows the rate of access to the process cache per partition",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_result_total{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Cache access {{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_result_total{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (partition, type)",
       "legendFormat": "P{{partition}} - {{type}}"
      }
     ]
    },
    {
     "title": "Cache load duration",
     "type": "heatmap",
     "description": "The time the cache spent computing or retrieving the new value",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Archiving - Search request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of the duration of search requests to find completed entities, which should be archived.",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", type=\"search\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving - Reindex request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of durations reindex requests take, to copy data from runtime to dated indices.",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", type=\"reindex\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving - Delete request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of durations delete requests take, to delete data from runtime indices.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", type=\"delete\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Cache load rate",
     "type": "timeseries",
     "description": "The rate of the loading data into the cache",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_load_duration_success_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Success p{{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Failure p{{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Process Instances Awaiting Archival)",
     "type": "timeseries",
     "description": "Process instances which can be archived but are waiting to do so.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_camunda_exporter_process_instances_awaiting_archival{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Archiving duration",
     "type": "heatmap",
     "description": "Histogram to show the distribution of the overall archiving duration, which includes searching, reindexing, and deletion.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving",
     "type": "timeseries",
     "description": "Shows the rate of archiving (in-progress) and archived process instance and batch operations. Batch operations or process instances need to be completed before being able to be archived. The rate is aggregated by partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_process_instances_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition, state)",
       "legendFormat": "{{state}} process instances [p{{partition}}]"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_batch_operations_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition, state)",
       "legendFormat": "{{state}} batch operations [p{{partition}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch Exporter (Flush Duration)",
     "type": "heatmap",
     "description": "Each time a non empty bulk request if flushed, this is how long the flush takes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 502 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Flush Failure Rate)",
     "type": "timeseries",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 502 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(zeebe_elasticsearch_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_elasticsearch_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Size)",
     "type": "heatmap",
     "description": "For every non empty flush of a bulk request, this is the number of entities flushed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 528 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Memory Size)",
     "type": "timeseries",
     "description": "Each bulk request has a number of records, the memory usage to flush this bulk request is crudely measured through content length and tracked here. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 528 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zeebe_elasticsearch_exporter_bulk_memory_size{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDBMS Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDBMS Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 391 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Flush Latency)",
     "type": "heatmap",
     "description": "How long an export request is open and collecting new records before flushing.",
     "gridPos": { "h": 8, "w": 11, "x": 10, "y": 391 },
     "targets": [
      {
       "expr": "rate(zeebe_rdbms_exporter_flush_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_rdbms_exporter_flush_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) > 0",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Flush Failure Rate)",
     "type": "gauge",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(zeebe_rdbms_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_camunda_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 463 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter JDBC Statements Batch factor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 11, "y": 463 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_enqueued_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) / sum(increase(zeebe_rdbms_exporter_executed_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "SQL Batch factor"
      },
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_merged_queue_item_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) / sum(increase(zeebe_rdbms_exporter_enqueued_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "QueueItem merge factor"
      }
     ]
    },
    {
     "title": "RDBMS Exporter Statements",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 463 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_executed_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (statementId)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}