{
 "title": "Zeebe",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(atomix_role, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   },
   { "name": "memory_state", "query": "committed, reserved" }
  ]
 },
 "panels": [
  {
   "title": "General Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topology",
     "type": "table",
     "description": "Displays the roles of each node per partition.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Banned instances",
     "type": "stat",
     "description": "Shows the count of banned process instances of the namespace.",
     "gridPos": { "h": 2, "w": 9, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max(zeebe_blacklisted_instances_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (namespace, partition))\nor sum(max(zeebe_banned_instances_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (namespace, partition))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "timeseries",
     "description": "Shows when and how often a pod was restarted.  The graph is zero when the pod is ready. With this it is also possible to determine how long it take for the pod to come ready again.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1 - kube_pod_container_status_ready{pod=~\"$pod\", cluster=~\"$cluster\", container!~\"curator|curl\", namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} restart"
      }
     ]
    },
    {
     "title": "Health",
     "type": "stat",
     "description": "Shows accumulated health per partition",
     "gridPos": { "h": 4, "w": 9, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(zeebe_health{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Processing per Partition",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"skipped|processed\"}[$__rate_interval])) by (pod, partition, processor)",
       "legendFormat": "{{pod}}-{{partition}}-{{processor}}-processed"
      },
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"written\"}[$__rate_interval])) by (pod, partition, processor)",
       "legendFormat": "{{pod}}-{{partition}}-{{processor}}-written"
      }
     ]
    },
    {
     "title": "Exporting per Partition",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_exporter_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (pod, partition, exporter)",
       "legendFormat": "{{pod}}-{{partition}}-exported"
      }
     ]
    },
    {
     "title": "Requests handled by Gateway per sec",
     "type": "timeseries",
     "description": "Requests which hit the gateway and a response have been sent to the client per second.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]), \"method\", \"$1\", \"grpc_method\", \"(.+)\") or on(method) rate(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{method}} Request"
      }
     ]
    },
    {
     "title": "Overall FNI  per s",
     "type": "stat",
     "description": "Flow node instances completed or terminated per second over all partitions.",
     "gridPos": { "h": 2, "w": 9, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval]))",
       "legendFormat": "Partition {{partition}} FNI per s"
      }
     ]
    },
    {
     "title": "Current Events",
     "type": "timeseries",
     "description": "Shows the current processed records",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (type, action, eventType)",
       "legendFormat": "{{type}} {{action}} {{eventType}}"
      }
     ]
    },
    {
     "title": "Completed Tasks in avg overtime per sec",
     "type": "stat",
     "description": "Takes the avg of all completed tasks per second over the given time range.",
     "gridPos": { "h": 2, "w": 9, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Completed Processes in avg overtime per sec",
     "type": "stat",
     "description": "Takes the avg of all completed processes per second over the given time range.",
     "gridPos": { "h": 2, "w": 5, "x": 8, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[$__rate_interval]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Archived Processes in avg overtime per sec",
     "type": "stat",
     "description": "Takes the avg of all archived processes per second over the given time range.",
     "gridPos": { "h": 2, "w": 4, "x": 13, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archived_process_instances_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "PVC Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Backpressure Dropping Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 8, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(zeebe_dropped_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition) / sum(rate(zeebe_received_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition) ) * 100",
       "legendFormat": "Partition {{partition}}"
      },
      {}
     ]
    },
    {
     "title": "Cluster Load",
     "type": "gauge",
     "description": "The current cluster load is defined by the current write rate divided by the write rate limit. The cluster load will display no data unless the flow control rate write limits are enabled.",
     "gridPos": { "h": 6, "w": 4, "x": 13, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(zeebe_flow_control_partition_load{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"} > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process memory usage",
     "type": "timeseries",
     "description": "Memory limits and requests are taken from the k8 pod metrics.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\".*(orchestration|zeebe|camunda).*\"}",
       "legendFormat": "{{pod}} RSS"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\".*(orchestration|zeebe|camunda).*\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\".*(orchestration|zeebe|camunda).*\"})",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "Health status timeline ",
     "type": "state-timeline",
     "description": "Timeline of the status of each partitions' component",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 168 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "zeebe_broker_health_nodes{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing Queue size",
     "type": "timeseries",
     "description": "Shows the processing queue size over time. Processing queue defines, what is already appended but not yet processed by the stream processor.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_appended_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) - max by (partition) (zeebe_stream_processor_last_processed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Batch processing command count",
     "type": "heatmap",
     "description": "Show the distribution of commands in the batches over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_batch_processing_commands_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of batch processing retries",
     "type": "timeseries",
     "description": "Shows how often we have retried batch processing due to reaching the maximum batch size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_batch_processing_retry_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by(partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Number of records exported but not acknowledged",
     "type": "timeseries",
     "description": "Shows how many positions are not updated by exporters per partition. Means what is the difference between last committed exporter position and committed log position.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "max by (exporter, pod, partition) (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) - max by (exporter, pod, partition) (zeebe_exporter_last_updated_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "{{exporter}} {{partition}} {{pod}}"
      }
     ]
    },
    {
     "title": "Processing Error Handling Phase",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "targets": [
      {
       "expr": "zeebe_stream_processor_error_handling_phase{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"} > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of records not exported",
     "type": "timeseries",
     "description": "Shows how many records are not exported yet.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 169 },
     "targets": [
      {
       "expr": "max (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) by (partition) - max (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", exporter=\"elasticsearch\"}) by (partition)",
       "legendFormat": "Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Last updated exported position",
     "type": "table",
     "description": "Shows the last exported position which was committed by the given exporter per partition.",
     "gridPos": { "h": 6, "w": 7, "x": 5, "y": 169 },
     "targets": [
      {
       "expr": "max by (exporter, partition) (zeebe_exporter_last_updated_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Last appended position",
     "type": "table",
     "description": "Shows the position, which was appended last by the leader per partition.",
     "gridPos": { "h": 4, "w": 7, "x": 12, "y": 169 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_appended_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Last committed position",
     "type": "table",
     "description": "Shows the last committed log position.",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 169 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Last processed position",
     "type": "table",
     "description": "Shows the last processed position by the stream processor per partition.",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 173 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_stream_processor_last_processed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Last replayed source position",
     "type": "table",
     "description": "Shows the last replayed source position by the stream processor per partition and pod",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 173 },
     "targets": [
      {
       "expr": "max by (partition, pod) (zeebe_replay_last_source_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Number of records not processed",
     "type": "timeseries",
     "description": "Shows how many records the stream processor has not processed yet.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 175 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) - max by (partition) (zeebe_stream_processor_last_processed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Last exported position",
     "type": "table",
     "description": "Shows the last exported position per partition.",
     "gridPos": { "h": 6, "w": 7, "x": 5, "y": 175 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", exporter=\"elasticsearch\"})"
      }
     ]
    },
    {
     "title": "Processing Phase",
     "type": "table",
     "description": "Displays the processing phase of each node per partition.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 181 },
     "targets": [
      {
       "expr": "zeebe_stream_processor_state{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Exporting Phase",
     "type": "table",
     "description": "Displays the exporting phase of each node per partition.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 181 },
     "targets": [
      {
       "expr": "zeebe_exporter_state{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Banned instances by partition",
     "type": "timeseries",
     "description": "Shows the count of banned process instances per partition.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 187 },
     "targets": [
      {
       "expr": "max(zeebe_blacklisted_instances_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (namespace, partition)\nor max(zeebe_banned_instances_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (namespace, partition)",
       "legendFormat": "{{namespace}} {{partition}}"
      }
     ]
    },
    {
     "title": "Buffered Messages by partition",
     "type": "timeseries",
     "description": "Shows the number of buffered messages per partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "targets": [
      {
       "expr": "max(zeebe_buffered_messages_count{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (partition, pod)",
       "legendFormat": "partition:{{partition}} {{pod}}"
      }
     ]
    },
    {
     "title": "Scheduled command cache size",
     "type": "timeseries",
     "description": "The size of the scheduled command cache, grouped by command intent.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "targets": [
      {
       "expr": "max(zeebe_stream_processor_scheduled_command_cache_size{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partitionId=~\"$partition\"}) by (pod, partitionId, intent)",
       "legendFormat": "{{intent}} p{{partitionId}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Instance Events per second (range = 1m)",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[$__rate_interval])) by (action)"
      }
     ]
    },
    {
     "title": "Job events per second (range = 1m)",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (action)",
       "legendFormat": "Stream Processor"
      }
     ]
    },
    {
     "title": "Process Instance Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}) by (action)",
       "legendFormat": "Process Instance ({{action}})"
      },
      {
       "expr": "sum(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Process Instance Events per second (range = 1m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[$__rate_interval])) by (action)",
       "legendFormat": "Process Instance ({{action}})"
      },
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Processed Commands",
     "type": "timeseries",
     "description": "Processed commands by the leading Stream Processor",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (action, partition)",
       "legendFormat": "Partition {{partition}} ({{action}})"
      }
     ]
    },
    {
     "title": "Exported Records",
     "type": "timeseries",
     "description": "Exported Records by the leading Stream Processor",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_exporter_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition, pod)",
       "legendFormat": "{{pod}} Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Replayed Events",
     "type": "timeseries",
     "description": "Replayed events by the following Stream Processor",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_replay_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition, pod)",
       "legendFormat": "{{pod}} Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Process instance creation per second",
     "type": "timeseries",
     "description": "Shows the process instance creation rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_executed_instances_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"activated\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "Process instance creation {{namespace}}"
      }
     ]
    },
    {
     "title": "Process instance completion per second",
     "type": "timeseries",
     "description": "Shows the process instance completion rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_executed_instances_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"completed\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "Process instance completion {{namespace}}"
      }
     ]
    },
    {
     "title": "Job creation per second",
     "type": "timeseries",
     "description": "Shows the Job creation rate over all partitions in the namespace",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"created\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "Job creation {{namespace}}"
      }
     ]
    },
    {
     "title": "Job completion per second",
     "type": "timeseries",
     "description": "Shows the Job completion rate over all partitions in the namespace.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"completed\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "Job completion {{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshot Count",
     "type": "timeseries",
     "description": "Total number of committed snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zeebe_snapshot_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap!=\"true\"}[$__rate_interval])",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Operation Duration",
     "type": "heatmap",
     "description": "Approximate duration of taking a single snapshot from the processor point-of-view (without replication or committing).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap!=\"true\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(zeebe_snapshot_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap!=\"true\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Snapshot Size",
     "type": "timeseries",
     "description": "Size in bytes of snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "zeebe_snapshot_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap!=\"true\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Files Sizes (1m)",
     "type": "heatmap",
     "description": "Distribution of snapshot file sizes - each snapshot may be comprised of many files, and this shows approximately how \"big\" files there are and how many \"small\" files.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_file_size_megabytes_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap!=\"true\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of files in a snapshot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zeebe_snapshot_chunks_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", bootstrap!=\"true\"}",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process memory usage",
     "type": "timeseries",
     "description": "Memory limits and requests are taken from the k8 pod metrics.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*(orchestration|zeebe|camunda).*\", container=~\".*(orchestration|zeebe|camunda).*\"}",
       "legendFormat": "{{pod}} RSS"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*(orchestration|zeebe|camunda).*\", container=~\".*(orchestration|zeebe|camunda).*\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*(orchestration|zeebe|camunda).*\", container=~\".*(orchestration|zeebe|camunda).*\"})",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "Native memory usage",
     "type": "timeseries",
     "description": "Native memory usage provided by NMT (mmapped files are not included)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "camunda_memory_nmt_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", state=~\"$memory_state\"}",
       "legendFormat": "{{pod}} {{type}} {{memory_state}}"
      },
      {
       "expr": "camunda_memory_nmt_total_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", state=~\"$memory_state\"}",
       "legendFormat": "{{pod}} {{type}} {{memory_state}}"
      }
     ]
    },
    {
     "title": "JVM Memory usage",
     "type": "timeseries",
     "description": "Total amount of memory reserved for the JVM, where:\n\n- Used means currently in use by live objects\n- Committed means allocated to the JVM by the OS, and guaranteed to be available for usage\n- Max means maximum possible committed memory, but not guaranteed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}} used"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}} used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}} committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}} max"
      }
     ]
    },
    {
     "title": "Buffer Pool Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum (jvm_buffer_pool_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace,pod,pool)",
       "legendFormat": "Used {{pod}}:{{pool}}"
      },
      {
       "expr": "sum (jvm_buffer_memory_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace,pod,id)",
       "legendFormat": "Used {{pod}}:{{id}}"
      }
     ]
    },
    {
     "title": "Netty pooled allocated bytes",
     "type": "timeseries",
     "description": "The amount of memory allocated by Netty's pooled allocator",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(netty_allocator_memory_used{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", allocator_type=\"PooledByteBufAllocator\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Netty unpooled allocated bytes",
     "type": "timeseries",
     "description": "The amount of memory allocated by Netty's unpooled allocator",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(netty_allocator_memory_used{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", allocator_type=\"UnpooledByteBufAllocator\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Count per second",
     "type": "timeseries",
     "description": "Shows the number of garbage collections (GC) per second, aggregated per pod and GC type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (gc, pod)",
       "legendFormat": "{{pod}} {{gc}}"
      },
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (gc, pod)",
       "legendFormat": "{{pod}} {{gc}}"
      }
     ]
    },
    {
     "title": "GC proportion per second",
     "type": "timeseries",
     "description": "Shows the garbage collection (GC) time proportion per second. Means shows the rate which is spent in GC in a second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} {{gc}}"
      },
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} {{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Throttling (AVG)",
     "type": "timeseries",
     "description": "The average percentage of CPU periods where the container ran but was throttled (stopped from running the whole CPU period).\n\n\ncontainer_cpu_cfs_periods_total -\nNumber of elapsed enforcement period intervals\ncontainer_cpu_cfs_throttled_periods_total -\nNumber of throttled period intervals\t\n\nhttps://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md\nhttps://stackoverflow.com/a/67316429/2165134\nhttps://www.youtube.com/watch?v=UE7QX98-kO0",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod) / sum(rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod, container, service) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!~\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Thread count",
     "type": "timeseries",
     "description": "Current thread count of a JVM, aggregated by namespace and pod",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "JVM threads on {{pod}}"
      },
      {
       "expr": "jvm_threads_daemon{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "JVM daemon threads on {{pod}}"
      },
      {
       "expr": "sum(jvm_threads_daemon_threads{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "JVM daemon threads on {{pod}}"
      },
      {
       "expr": "sum(jvm_threads_live_threads{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod) - sum(jvm_threads_daemon_threads{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "JVM threads {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVC Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
     "targets": [
      {
       "expr": "ceil(sum by(pod, service, container) (rate(container_fs_reads_total{cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
     "targets": [
      {
       "expr": "sum by(pod, container, service) (rate(container_fs_writes_total{cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_files_open_files{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} use fds"
      },
      {
       "expr": "process_files_max_files{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} limit"
      }
     ]
    },
    {
     "title": "PVC Disk Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}} ({{namespace}})"
      }
     ]
    },
    {
     "title": "Read bytes/s",
     "type": "timeseries",
     "description": "Shows the bytes read per second for the zeebe pods in the select namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval])) by (pod, service, container)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Written bytes/s",
     "type": "timeseries",
     "description": "Shows the written bytes per second by the Zeebe pods in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval])) by (pod, service, container)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s transmitted",
     "type": "timeseries",
     "description": "Shows how many bytes the Zeebe Pods transmit per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, container, service)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s received",
     "type": "timeseries",
     "description": "Shows how many bytes the Zeebe Pods have received per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, container, service)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messaging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": " Request response latency",
     "type": "heatmap",
     "description": "Shows the general latency for request-responses in zeebe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 297 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or increase(zeebe_messaging_request_response_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Request size distribution",
     "type": "heatmap",
     "description": "Shows the general request size distribution",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 297 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Request response latency quantiles",
     "type": "timeseries",
     "description": "Shows the general latency for request-responses in zeebe.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(zeebe_messaging_request_response_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (topic, le))",
       "legendFormat": "p50 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(zeebe_messaging_request_response_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (topic, le))",
       "legendFormat": "p90 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(zeebe_messaging_request_response_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (topic, le))",
       "legendFormat": "p99 {{topic}}"
      }
     ]
    },
    {
     "title": "Request size quantiles",
     "type": "timeseries",
     "description": "Shows the general latency for request-responses in zeebe.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (topic, le))",
       "legendFormat": "p50 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (topic, le))",
       "legendFormat": "p90 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (topic, le))",
       "legendFormat": "p99 {{topic}}"
      }
     ]
    },
    {
     "title": "Inflight request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 315 },
     "targets": [
      {
       "expr": "sum(zeebe_messaging_inflight_requests) by (pod, address)",
       "legendFormat": "{{pod}} => {{address}} "
      }
     ]
    },
    {
     "title": "Request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 315 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_messaging_request_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, address, topic)",
       "legendFormat": "{{topic}}: {{pod}} => {{address}}"
      }
     ]
    },
    {
     "title": "Response failure count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 323 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_messaging_response_count_total{namespace=~\"$namespace\", pod=~\"$pod\", outcome!=\"SUCCESS\"}[$__rate_interval])) by (address, topic, outcome)",
       "legendFormat": "{{topic}} {{address}} {{outcome}}"
      }
     ]
    },
    {
     "title": "Request count per type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 323 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_messaging_request_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Instance Execution Time",
     "type": "heatmap",
     "description": "Shows the execution time of a process instance. This means the time (latency) between creating the instance and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_process_instance_execution_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(rate(zeebe_process_instance_execution_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Instance Execution Time (avg)",
     "type": "timeseries",
     "description": "Shows the execution time of a process instance. This means the time (latency) between creating the instance and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le))",
       "legendFormat": "quantile-50th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le))",
       "legendFormat": "quantile-99th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le))",
       "legendFormat": "quantile-50th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le))",
       "legendFormat": "quantile-99th"
      }
     ]
    },
    {
     "title": "Job Activation Time",
     "type": "heatmap",
     "description": "Shows the time (latency) between creating the job and activating it.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_job_activation_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(zeebe_job_activation_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Job Life Time",
     "type": "heatmap",
     "description": "Shows the complete lifetime of an job. This means the time (latency) between creating the job and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_job_life_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(zeebe_job_life_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Overall Processing Latency",
     "type": "heatmap",
     "description": "Shows the time (latency) between writing the command to the dispatcher and processing the record.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or increase(zeebe_stream_processor_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Record Processing Duration",
     "type": "timeseries",
     "description": "Time taken to process a record",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 176 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(increase(zeebe_stream_processor_processing_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_stream_processor_processing_duration_seconds_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le, valueType, intent))",
       "legendFormat": "p50 {{valueType}}.{{intent}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(increase(zeebe_stream_processor_processing_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_stream_processor_processing_duration_seconds_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le, valueType, intent))",
       "legendFormat": "p90 {{valueType}}.{{intent}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(increase(zeebe_stream_processor_processing_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_stream_processor_processing_duration_seconds_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le, valueType, intent))",
       "legendFormat": "p99 {{valueType}}.{{intent}}"
      }
     ]
    },
    {
     "title": "Record Processing Duration",
     "type": "heatmap",
     "description": "Time taken to process a record",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_processing_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_stream_processor_processing_duration_seconds_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch Event Replay Duration",
     "type": "heatmap",
     "description": "Time taken to replay a batch of events",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 186 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_replay_event_batch_replay_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or increase(zeebe_replay_event_batch_replay_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Post commit task execution duration",
     "type": "heatmap",
     "description": "Time spent executing post-commit tasks after batch processing (in seconds)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 193 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_batch_processing_post_commit_tasks_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or increase(zeebe_stream_processor_batch_processing_post_commit_tasks_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch processing duration (in seconds)",
     "type": "heatmap",
     "description": "Time spent in processing a batch of commands (excluding transaction commit, side effects, etc.)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 193 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_batch_processing_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or increase(zeebe_stream_processor_batch_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Commit Latency Quantiles",
     "type": "timeseries",
     "description": "Shows the quantiles of: time taken to commit a record to the log (includes write latency)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, rate(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_log_appender_commit_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "p90 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_log_appender_commit_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "p99 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.50, rate(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_log_appender_commit_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "MEDIAN partition {{partition}} "
      },
      {
       "expr": "sum(rate(zeebe_log_appender_commit_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) / sum(rate(zeebe_log_appender_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) or sum(rate(zeebe_log_appender_commit_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) / sum(rate(zeebe_log_appender_commit_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) ",
       "legendFormat": "AVG partition {{partition}}"
      }
     ]
    },
    {
     "title": "Record Write Quantiles",
     "type": "timeseries",
     "description": "Shows the quantiles of: time taken to append a record to the log",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, rate(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_log_appender_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "p90 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_log_appender_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "p99 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.50, rate(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(zeebe_log_appender_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "MEDIAN partition {{partition}} "
      },
      {
       "expr": "sum(rate(zeebe_log_appender_append_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) / sum(rate(zeebe_log_appender_append_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) or sum(rate(zeebe_log_appender_append_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) / sum(rate(zeebe_log_appender_append_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition)  ",
       "legendFormat": "AVG partition {{partition}}"
      }
     ]
    },
    {
     "title": "Commit latency",
     "type": "heatmap",
     "description": "Time taken to commit a record to the log (includes write latency)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 207 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le) or sum(increase(zeebe_log_appender_commit_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Record write latency",
     "type": "heatmap",
     "description": "Time taken to append a record to the log",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 207 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le) or sum(increase(zeebe_log_appender_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total gRPC requests",
     "type": "timeseries",
     "description": "Shows counts of all gRPC messages, which have been sent to the Zeebe Cluster.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1415 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(label_replace(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), \"method\", \"$1\", \"grpc_method\", \"(.+)\"), \"statusCode\", \"$1\", \"code\", \"(.+)\") or on(method, statusCode) rate(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (method, statusCode)",
       "legendFormat": "{{method}} ({{statusCode}})"
      }
     ]
    },
    {
     "title": "gRPC requests per second (range = 1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1415 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(label_replace(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), \"method\", \"$1\", \"grpc_method\", \"(.+)\"), \"statusCode\", \"$1\", \"code\", \"(.+)\") or on(method, statusCode) rate(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (method, statusCode)",
       "legendFormat": "{{method}} ({{statusCode}})"
      },
      {
       "expr": "sum(label_replace(label_replace(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), \"method\", \"$1\", \"grpc_method\", \"(.+)\"), \"statusCode\", \"$1\", \"code\", \"(.+)\") or on(method, statusCode) rate(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Total requests completed"
      }
     ]
    },
    {
     "title": "Create Process Instance Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1422 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"CreateProcessInstance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(grpc_server_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", method=\"CreateProcessInstance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Activate Jobs Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1422 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"ActivateJobs\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(grpc_server_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", method=\"ActivateJobs\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Complete Job Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1422 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"CompleteJob\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(grpc_server_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", method=\"CompleteJob\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway Request Latency",
     "type": "heatmap",
     "description": "Shows the latency (RTT) of a sent from the gateway to the broker.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1416 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_gateway_request_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(zeebe_gateway_request_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Failure Error Code",
     "type": "timeseries",
     "description": "Shows rate of each error type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1424 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(zeebe_gateway_failed_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", error=~\".*\"}[$__rate_interval]) / rate(zeebe_gateway_total_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "Failure Rate by Request Type",
     "type": "timeseries",
     "description": "Shows failure rate of requests sent from gateway to the broker.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1424 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (requestType) (rate(zeebe_gateway_failed_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) / \nsum by (requestType) (rate(zeebe_gateway_total_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "{{requestType}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft requests per second",
     "type": "timeseries",
     "description": "Shows the rate of different raft requests send from the leader to different followers",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1417 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_raft_messages_send_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (partition, to, type)",
       "legendFormat": "{{pod}} {{partition}} send {{type}} to {{to}}"
      }
     ]
    },
    {
     "title": "Total install requests send",
     "type": "timeseries",
     "description": "Shows the total count of send install requests from the leader to the followers",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1417 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "atomix_raft_messages_send_total{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"InstallRequest\"}",
       "legendFormat": "{{pod}} {{partition}} send {{type}} to {{to}}"
      }
     ]
    },
    {
     "title": "Leader commit rate",
     "type": "timeseries",
     "description": "How many entries are committed per second",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1424 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_commit_entries_rate_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "p{{partition}}"
      }
     ]
    },
    {
     "title": "Leader append data rate",
     "type": "timeseries",
     "description": "Rate in KiB at which we append data on followers",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1432 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_append_entries_data_rate_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition, follower)",
       "legendFormat": "p{{partition}} to {{follower}}"
      }
     ]
    },
    {
     "title": "Leader append rate",
     "type": "timeseries",
     "description": "Rate of entries we append data on followers, counting entries, per partition, per follower",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1432 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_append_entries_rate_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition, follower)",
       "legendFormat": "p{{partition}} to {{follower}}"
      }
     ]
    },
    {
     "title": "Snapshot Replication Duration",
     "type": "timeseries",
     "description": "Approximate Install RPC as measured by the follower.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1439 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "atomix_snapshot_replication_duration_milliseconds{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Replications",
     "type": "timeseries",
     "description": "Ongoing snapshot replications per partition, from the follower point-of-view.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1439 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "atomix_snapshot_replication_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} {{partitionGroupName}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Append Entry Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1446 },
     "targets": [
      {
       "expr": "sum(increase(atomix_append_entries_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or increase(atomix_append_entries_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "AppendEntry latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1446 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_append_entries_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(atomix_append_entries_latency_second_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) / sum(rate(atomix_append_entries_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(atomix_append_entries_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "Avg"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(atomix_append_entries_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(atomix_append_entries_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le))",
       "legendFormat": "Median"
      }
     ]
    },
    {
     "title": "Time Between Heartbeats",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1453 },
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_time_in_s_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or increase(atomix_heartbeat_time_in_s_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heartbeat Miss Counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1453 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_miss_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval])) by (pod, partition)",
       "legendFormat": "{{pod}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Role changes over time",
     "type": "state-timeline",
     "description": "Shows when a role change has happened",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1461 },
     "targets": [
      {
       "expr": "atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Role changes over time",
     "type": "timeseries",
     "description": "Shows when a role change has happened. \n1 = Follower\n2 = Candidate\n3 = Leader\n2 - ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1461 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Commit Index",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1469 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "atomix_partition_raft_commit_index{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Index of last appended entry",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1534 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "atomix_partition_raft_append_index{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}}-p{{partition}}"
      }
     ]
    },
    {
     "title": "Non replicated records",
     "type": "gauge",
     "description": "The number of records a follower is lagging behind for a given partition (p) and follower (f)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1589 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(atomix_non_replicated_entries{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (partition, follower)",
       "legendFormat": "p{{partition}} f{{follower}}"
      }
     ]
    },
    {
     "title": "Non committed records",
     "type": "gauge",
     "description": "The number of locally appended but non committed records on the leader per partition (p)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1599 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(atomix_non_committed_entries{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition)",
       "legendFormat": "p {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Journal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of log segments",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "atomix_segment_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    },
    {
     "title": "Journal append data rate",
     "type": "timeseries",
     "description": "The rate, in KiB/s, of data appended to the local journal",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_journal_append_data_rate_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (pod, partition)",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    },
    {
     "title": "Journal append rate",
     "type": "timeseries",
     "description": "The rate of entries appended to the local journal (by entry count), per pod, per partition",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_journal_append_rate_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (pod, partition)",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    },
    {
     "title": "Journal Flush Latency",
     "type": "timeseries",
     "description": "Overall latency to flush the complete journal",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_journal_flush_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (pod) / sum(rate(atomix_journal_flush_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]))  by (pod) or sum(rate(atomix_journal_flush_time_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (pod) / sum(rate(atomix_journal_flush_time_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]))  by (pod)",
       "legendFormat": "Avg {{ pod }}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(atomix_journal_flush_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(atomix_journal_flush_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le))",
       "legendFormat": "Median"
      }
     ]
    },
    {
     "title": "Journal Flush Latency",
     "type": "heatmap",
     "description": "Overall latency distribution to flush the journal",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 203 },
     "targets": [
      {
       "expr": "sum(increase(atomix_journal_flush_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le) or sum(increase(atomix_journal_flush_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Journal append latency",
     "type": "heatmap",
     "description": "Time spent appending in the local journal",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 210 },
     "targets": [
      {
       "expr": "sum(increase(atomix_journal_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le) or sum(increase(atomix_journal_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Journal append latency",
     "type": "timeseries",
     "description": "Quantile distribution of time spent appending in the journal, per partition, per pod",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, rate(atomix_journal_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(atomix_journal_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "p90 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(atomix_journal_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(atomix_journal_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "p99 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.50, rate(atomix_journal_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]) or rate(atomix_journal_append_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "MEDIAN partition {{partition}} "
      },
      {
       "expr": "sum(rate(atomix_journal_append_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) / sum(rate(atomix_journal_append_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) or sum(rate(atomix_journal_append_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) / sum(rate(atomix_journal_append_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition) ",
       "legendFormat": "AVG partition {{partition}}"
      }
     ]
    },
    {
     "title": "Segment Creation Time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 217 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_creation_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or increase(atomix_segment_creation_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Allocation Time",
     "type": "heatmap",
     "description": "Time spent pre-allocating a segment",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 217 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_allocation_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le) or sum(increase(atomix_segment_allocation_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Flush Latency",
     "type": "heatmap",
     "description": "Overall latency distribution to flush a single segment",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 223 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_flush_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or increase(atomix_segment_flush_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Flush Latency",
     "type": "timeseries",
     "description": "Overall latency of flushing a single segment",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_segment_flush_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (pod) / sum(rate(atomix_segment_flush_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]))  by (pod)",
       "legendFormat": "Avg {{ pod }}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(atomix_segment_flush_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(atomix_segment_flush_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le))",
       "legendFormat": "Median"
      }
     ]
    },
    {
     "title": "Compacting time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 230 },
     "targets": [
      {
       "expr": "sum(increase(atomix_compaction_time_ms_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or increase(atomix_compaction_time_ms_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Last Written Index Update",
     "type": "heatmap",
     "description": "Time spent updating the last written index",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 230 },
     "targets": [
      {
       "expr": "sum(increase(atomix_last_flushed_index_update_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le) or sum(increase(atomix_last_flushed_index_update_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Seek Latency",
     "type": "heatmap",
     "description": "Overall latency distribution to seek to an index",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 236 },
     "targets": [
      {
       "expr": "sum(increase(atomix_journal_seek_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le) or sum(increase(atomix_journal_seek_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of journal seek (per second)",
     "type": "timeseries",
     "description": "Number of times journal seek was executed. This included both seek to an index and seek to asqn.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(atomix_journal_seek_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval]) or rate(atomix_journal_seek_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (pod, partition)",
       "legendFormat": "{{ pod }} - p{{ partition }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sequencer Queue Size",
     "type": "timeseries",
     "description": "Number of batches in the sequencer's queue",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_sequencer_queue_size{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (pod, partition)",
       "legendFormat": "{{pod}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Sequencer Batch Entry Count",
     "type": "heatmap",
     "description": "Shows the distribution of the # of entries per batch",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_sequencer_batch_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sequencer Batch Size (KB)",
     "type": "heatmap",
     "description": "Shows the distribution of the size of each enqueued batch, in kilobytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_sequencer_batch_length_bytes_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Written commands",
     "type": "timeseries",
     "description": "Rate of commands written per second by the log storage appender on the leader",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_log_appender_record_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", recordType=\"COMMAND\"}[$__rate_interval])) by (valueType, intent)",
       "legendFormat": "{{valueType}}.{{intent}}"
      }
     ]
    },
    {
     "title": "Written events",
     "type": "timeseries",
     "description": "Rate of events written per second by the log storage appender on the leader",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_log_appender_record_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", recordType=\"EVENT\"}[$__rate_interval])) by (valueType, intent)",
       "legendFormat": "{{valueType}}.{{intent}}"
      }
     ]
    },
    {
     "title": "Written rejections",
     "type": "timeseries",
     "description": "Rate of written rejections per second by the log storage appender on the leader",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_log_appender_record_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", recordType=\"COMMAND_REJECTION\"}[$__rate_interval])) by (valueType, intent)",
       "legendFormat": "{{valueType}}.{{intent}}"
      }
     ]
    },
    {
     "title": "Number of deferred appends due to backpressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "targets": [
      {
       "expr": "rate(zeebe_deferred_append_count_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Appender Flow-Control",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
     "targets": [
      {
       "expr": "zeebe_backpressure_inflight_append_count{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "In-Flight for partition {{partition}}"
      },
      {
       "expr": "zeebe_backpressure_append_limit{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "Limit for partition {{partition}}"
      }
     ]
    },
    {
     "title": "Accepted writes by source",
     "type": "timeseries",
     "description": "The number of records accepted by flow control per second, organized by partition and write source (e.g. processing result, scheduled tasks etc.)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
     "targets": [
      {
       "expr": "sum by (context, partition) (rate(zeebe_flow_control_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\", outcome=\"accepted\"}[$__rate_interval]))",
       "legendFormat": "Partition {{partition}}: {{context}}"
      }
     ]
    },
    {
     "title": "Rejected writes by source and reason",
     "type": "timeseries",
     "description": "The number of records rejected by flow control per second, organized by partition and write source (e.g. processing result, scheduled tasks etc.)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
     "targets": [
      {
       "expr": "sum by (context, partition, outcome) (rate(zeebe_flow_control_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\", outcome!=\"accepted\"}[$__rate_interval]))",
       "legendFormat": "Partition {{partition}} rejected {{context}}: {{outcome}}"
      }
     ]
    },
    {
     "title": "Write Rate Limits",
     "type": "timeseries",
     "description": "The current and maximum permissible write rate limit per partition. When current is smaller than the maximum, throttling is in effect ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
     "targets": [
      {
       "expr": "zeebe_flow_control_write_rate_limit{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"} != 0",
       "legendFormat": "Current limit on {{partition}}"
      },
      {
       "expr": "zeebe_flow_control_write_rate_maximum{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"} != 0",
       "legendFormat": "Maximum limit on {{partition}}"
      }
     ]
    },
    {
     "title": "Measured exporting rate",
     "type": "timeseries",
     "description": "Measured average exporting rate which may be used to throttle write rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
     "targets": [
      {
       "expr": "zeebe_flow_control_exporting_rate{namespace=~\"$namespace\", pod=~\"$partition\", partition=~\"$partition\"} != 0",
       "legendFormat": "Exporting rate for {{partition}}"
      }
     ]
    },
    {
     "title": "Written commands",
     "type": "piechart",
     "description": "Distribution of written commands by the leading log storage appender",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_log_appender_record_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", recordType=\"COMMAND\"}[$__rate_interval])) by (recordType, valueType, intent)",
       "legendFormat": "{{valueType}}.{{intent}}"
      }
     ]
    },
    {
     "title": "Written events",
     "type": "piechart",
     "description": "Distribution of written events by the leading log storage appender",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_log_appender_record_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", recordType=\"EVENT\"}[$__rate_interval])) by (valueType, intent)",
       "legendFormat": "{{valueType}}.{{intent}}"
      }
     ]
    },
    {
     "title": "Written rejections",
     "type": "piechart",
     "description": "Distribution of written rejections by the leading log storage appender",
     "gridPos": { "h": 9, "w": 5, "x": 12, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_log_appender_record_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", recordType=\"COMMAND_REJECTION\"}[$__rate_interval])) by (valueType, intent)",
       "legendFormat": "{{valueType}}.{{intent}}"
      }
     ]
    },
    {
     "title": "Partition Load",
     "type": "gauge",
     "description": "The current partition load is defined by the current write rate divided by the write rate limit per partition. The partition load panel will display no data unless the flow control rate write limits are enabled.",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zeebe_flow_control_partition_load{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"} > 0",
       "legendFormat": "Partition: {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RocksDB Memory usage",
     "type": "timeseries",
     "description": "Sum of memtable, table reader and cache memory capacity.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(sum(zeebe_rocksdb_memory_estimate_table_readers_mem{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)) + (sum(zeebe_rocksdb_memory_size_all_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",  partition=~\"$partition\"}) by (pod, partition)) + (sum(zeebe_rocksdb_memory_block_cache_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)) + (sum(rate(zeebe_rocksdb_live_estimate_num_keys{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",  partition=~\"$partition\"}[$__rate_interval])) by (pod, partition) * 10)",
       "legendFormat": "{{pod}} memory {{partition}}"
      }
     ]
    },
    {
     "title": "Estimated Number of Keys",
     "type": "timeseries",
     "description": "Estimated total number of keys in the database per column family",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zeebe_rocksdb_live_estimate_num_keys{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}} keys {{columnFamilyName}}"
      }
     ]
    },
    {
     "title": "Estimated Live Data",
     "type": "timeseries",
     "description": "Estimated amount of live data in bytes per column family",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_live_estimate_live_data_size{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} live data {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. size of all mem tables",
     "type": "timeseries",
     "description": "Returns approximate size of active, unflushed immutable, and pinned immutable memtables (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L807",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_size_all_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} All Memtable's {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. current all mem table size",
     "type": "timeseries",
     "description": "Approximate size of active and unflushed immutable memtables (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L803",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_cur_size_all_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Memtable {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. current active mem table size",
     "type": "timeseries",
     "description": "Approximate size of active memtable (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L799",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_cur_size_active_mem_table{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Memtable {{partition}}"
      }
     ]
    },
    {
     "title": "Block cache capacity",
     "type": "timeseries",
     "description": "The block cache capacity per column family",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Block cache {{partition}}"
      }
     ]
    },
    {
     "title": "Block cache usage",
     "type": "timeseries",
     "description": "The current usage of the block cache per column family\n\nhttps://github.com/facebook/rocksdb/blob/618bf638aabce21262228509e9f99c1c13de2b57/include/rocksdb/cache.h#L261",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_usage{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Block cache usage {{partition}}"
      }
     ]
    },
    {
     "title": "Pinned block cache usage",
     "type": "timeseries",
     "description": "The current pinned usage of the block cache per column family\n\nhttps://github.com/facebook/rocksdb/blob/618bf638aabce21262228509e9f99c1c13de2b57/include/rocksdb/cache.h#L261",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_pinned_usage{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} pinned cache {{partition}}"
      }
     ]
    },
    {
     "title": "Total size of live SST files",
     "type": "timeseries",
     "description": "Total size (bytes) of all SST  files belong to the latest LSM tree.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L882",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_sst_live_sst_files_size{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  live sst {{partition}}"
      }
     ]
    },
    {
     "title": "Total size of all SST files",
     "type": "timeseries",
     "description": "Total size (bytes) of all SST files.\n\nWARNING: may slow down online queries if there are too many files.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L878",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_sst_total_sst_files_size{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  total sst {{partition}}"
      }
     ]
    },
    {
     "title": "Write stopped",
     "type": "timeseries",
     "description": "Return 1 if write has been stopped.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L908",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 237 },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_is_write_stopped{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  stopped write {{partition}}"
      }
     ]
    },
    {
     "title": "Actual write delay rate",
     "type": "timeseries",
     "description": "The current actual delayed write rate. 0 means no delay.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L905",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zeebe_rocksdb_writes_actual_delayed_write_rate{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}  delayed write {{partition}}"
      }
     ]
    },
    {
     "title": "Number of entries in immutable mem Tables",
     "type": "timeseries",
     "description": " Return sum of number of entries in all the immutable mem tables.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zeebe_rocksdb_live_num_entries_imm_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{columnFamilyName}}"
      }
     ]
    },
    {
     "title": "Running flush",
     "type": "timeseries",
     "description": "Returns the number of currently running flushes.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L783",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_num_running_flushes{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  flush {{partition}}"
      }
     ]
    },
    {
     "title": "Running compactions",
     "type": "timeseries",
     "description": "The number of currently running compactions.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L791",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_num_running_compactions{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  compaction {{partition}}"
      }
     ]
    },
    {
     "title": "Table Reader Memory ",
     "type": "timeseries",
     "description": "Returns estimated memory used for reading SST tables, excluding memory used in block cache (e.g., filter and index blocks).\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L832",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_estimate_table_readers_mem{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Table Reader {{partition}}"
      }
     ]
    },
    {
     "title": "Column Family Access Latency 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, operation, columnFamily, partition) (rate(zeebe_rocksdb_latency_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])))",
       "legendFormat": "{{operation}} on {{columnFamily}} at partition {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Completed",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(zeebe_batchoperations_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", action=\"COMPLETED\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total completed by Type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(type) (zeebe_batchoperations_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", action=\"COMPLETED\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Items by Type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(type) (zeebe_batchoperations_items_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executed Queries against 2nd Database",
     "type": "timeseries",
     "description": "Number of executed queries to the secondary database for batch operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by(partition, pod) (increase(zeebe_batchoperations_queries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Total Failed Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum by(partition, pod) (increase(zeebe_batchoperations_queries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", queryStatus=\"failed\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Query Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_batchoperations_execution_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", batchOperationLatency=\"TOTAL_QUERY_LATENCY\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Execution Latency",
     "type": "heatmap",
     "description": "Time needed for execution all items",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_batchoperations_execution_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", batchOperationLatency=\"TOTAL_EXECUTION_LATENCY\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum by(le) (increase(zeebe_batchoperations_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Duration per Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sum by(type) (increase(zeebe_batchoperations_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Start - Execute Latency",
     "type": "heatmap",
     "description": "The Latency when creating the first execute command until it gets executed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_batchoperations_execution_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", batchOperationLatency=\"START_EXECUTE_LATENCY\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Items",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "sum by(le) (increase(zeebe_batchoperations_items_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Cycle Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_batchoperations_execution_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", batchOperationLatency=\"EXECUTE_CYCLE_LATENCY\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch Operation Lifecycle Events",
     "type": "timeseries",
     "description": "Total number of executed batch operation lifecycle events (created, started, executed, completed, failed, cancelled, suspended, resumed) per partition and batch operation type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "sum by(action) (increase(zeebe_batchoperations_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 371 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Flush Failure Rate)",
     "type": "timeseries",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 371 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(zeebe_elasticsearch_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_elasticsearch_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 381 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Memory Size)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 381 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zeebe_elasticsearch_exporter_bulk_memory_size{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Elasticsearch disk usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*elastic.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*elastic.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Camunda Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Camunda Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Failure Rate)",
     "type": "gauge",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 9, "w": 3, "x": 10, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(zeebe_camunda_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_camunda_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Latency)",
     "type": "timeseries",
     "description": "How long an export request is open and collecting new records before flushing.",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(zeebe_camunda_exporter_flush_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_camunda_exporter_flush_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 170 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Process cache access",
     "type": "timeseries",
     "description": "Shows the rate of access to the process cache per partition",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 175 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_result_total{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Cache access {{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_result_total{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (partition, type)",
       "legendFormat": "P{{partition}} - {{type}}"
      }
     ]
    },
    {
     "title": "Process cache eviction",
     "type": "timeseries",
     "description": "Shows the rate of evictions of the process cache",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 175 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_evictions_total{namespace=~\"$namespace\",partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Evictions {{partition}}"
      }
     ]
    },
    {
     "title": "Cache load duration",
     "type": "heatmap",
     "description": "The time the cache spent computing or retrieving the new value",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 182 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache load rate",
     "type": "timeseries",
     "description": "The rate of the loading data into the cache",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 182 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_load_duration_success_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Success p{{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition)",
       "legendFormat": "Failure p{{partition}}"
      }
     ]
    },
    {
     "title": "Archiving",
     "type": "timeseries",
     "description": "Shows the rate of archiving (in-progress) and archived process instance and batch operations. Batch operations or process instances need to be completed before being able to be archived. The rate is aggregated by partition.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 188 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_process_instances_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition, state)",
       "legendFormat": "{{state}} process instances [p{{partition}}]"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_batch_operations_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (partition, state)",
       "legendFormat": "{{state}} batch operations [p{{partition}}]"
      }
     ]
    },
    {
     "title": "Archiving duration",
     "type": "heatmap",
     "description": "Histogram to show the distribution of the overall archiving duration, which includes searching, reindexing, and deletion.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 197 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving - Search request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of the duration of search requests to find completed entities, which should be archived.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 205 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", type=\"search\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving - Reindex request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of durations reindex requests take, to copy data from runtime to dated indices.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 205 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", type=\"reindex\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving - Delete request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of durations delete requests take, to delete data from runtime indices.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 205 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", type=\"delete\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDBMS Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDBMS Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 223 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Flush Latency)",
     "type": "heatmap",
     "description": "How long an export request is open and collecting new records before flushing.",
     "gridPos": { "h": 9, "w": 11, "x": 10, "y": 223 },
     "targets": [
      {
       "expr": "rate(zeebe_rdbms_exporter_flush_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_rdbms_exporter_flush_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) > 0",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Flush Failure Rate)",
     "type": "gauge",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(zeebe_rdbms_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_camunda_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 232 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter JDBC Statements Batch factor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 10, "y": 232 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_enqueued_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) / sum(increase(zeebe_rdbms_exporter_executed_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "SQL Batch factor"
      },
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_merged_queue_item_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) / sum(increase(zeebe_rdbms_exporter_enqueued_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "QueueItem merge factor"
      }
     ]
    },
    {
     "title": "RDBMS Exporter Statements",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 232 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_executed_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (statementId)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Start up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Atomix Partition Server Startup time",
     "type": "bargauge",
     "description": "Time taken to start and bootstrap partition servers.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 814 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "atomix_partition_server_startup_time{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": " Start {{pod}} p{{partition}}"
      },
      {
       "expr": "atomix_partition_server_bootstrap_time{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "Bootstrap  {{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Streamprocessor Recovery Time",
     "type": "bargauge",
     "description": "Time taken to recover and reprocess events",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 826 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "zeebe_stream_processor_startup_recovery_time{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}}:Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Leader transition duration",
     "type": "bargauge",
     "description": "The time needed to install all leader services on a newly elected leader until it is ready to process new requests.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 826 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zeebe_leader_transition_latency{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: Partition {{ partition }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current In-Progress Backups",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1423 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(zeebe_backup_operations_in_progress{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", operation=\"take\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Completed Backups",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1423 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(zeebe_backup_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", operation=\"take\", result=\"completed\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Status Query Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1431 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_backup_operations_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", operation=\"status\"}[$__interval]) or increase(zeebe_backup_operations_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", operation=\"status\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Take Backup Latency",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1431 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (partition) ((rate(zeebe_backup_operations_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\", operation=\"take\"}[1h]) / rate(zeebe_backup_operations_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\", operation=\"take\"}[1h])) or (rate(zeebe_backup_operations_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\", operation=\"take\"}[1h]) / rate(zeebe_backup_operations_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\", operation=\"take\"}[1h])))",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Total Backup Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1439 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_backup_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (operation, result)",
       "legendFormat": "{{operation}}: {{result}}"
      }
     ]
    },
    {
     "title": "Failed Backups",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1439 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(zeebe_backup_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", operation=\"take\", result=\"failed\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Total Checkpoint Records",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1447 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(zeebe_checkpoint_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Checkpoint Positions",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1447 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(zeebe_checkpoint_position{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Current Checkpoint ID",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1455 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(zeebe_checkpoint_id{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Actor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actor Task Execution Latency",
     "type": "heatmap",
     "description": "Execution time of a certain actor task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 376 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_actor_task_execution_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le) or sum(increase(zeebe_actor_task_execution_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Actor Job Scheduling Latency",
     "type": "heatmap",
     "description": "The time between scheduling and executing a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 376 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_actor_job_scheduling_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le) or sum(increase(zeebe_actor_job_scheduling_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Actor Task Execution Latency",
     "type": "timeseries",
     "description": "Execution time of a certain actor task instance and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 384 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_actor_task_execution_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, actorName) or sum(rate(zeebe_actor_task_execution_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, actorName))",
       "legendFormat": "p50 {{actorName}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_actor_task_execution_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, actorName) or sum(rate(zeebe_actor_task_execution_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, actorName))",
       "legendFormat": "p99 {{actorName}}"
      }
     ]
    },
    {
     "title": "Actor Job Scheduling Latency",
     "type": "timeseries",
     "description": "The time between scheduling and executing a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 384 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_actor_job_scheduling_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, subscriptionType) or sum(rate(zeebe_actor_job_scheduling_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, subscriptionType))",
       "legendFormat": "p50 {{subscriptionType}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_actor_job_scheduling_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, subscriptionType) or sum(rate(zeebe_actor_job_scheduling_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (le, subscriptionType))",
       "legendFormat": "p99 {{subscriptionType}}"
      }
     ]
    },
    {
     "title": "Actor Task Execution Count",
     "type": "timeseries",
     "description": "Number of times a certain actor task was executed successfully.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 392 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_actor_task_execution_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (actorName)",
       "legendFormat": "{{actorName}}"
      }
     ]
    },
    {
     "title": "Actor Task Queue Length",
     "type": "timeseries",
     "description": "The length of the job queue for an actor task.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 392 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_actor_task_queue_length{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (actorName)",
       "legendFormat": "{{topic}}: {{pod}} => {{address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SWIM Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swim Probe Latency",
     "type": "heatmap",
     "description": "Shows the execution time of the swim protocol probe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 377 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", topic=~\"atomix-membership-probe-request\"}[$__rate_interval]) or increase(zeebe_messaging_request_response_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", topic=~\"atomix-membership-probe-request\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Swim Protocol Member Incarnation Number",
     "type": "timeseries",
     "description": "Members Incarnation number. This metric shows the incarnation number of each member in the several nodes. This is useful for observing the time taken for each member's information propagation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 377 },
     "targets": [
      {
       "expr": "zeebe_smp_members_incarnation_number{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} member: {{memberId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Jobs Activated",
     "type": "timeseries",
     "description": "Rate of jobs of jobs activated by the client.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_client_worker_job_activated_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, workerName, jobType)",
       "legendFormat": "Worker Name:{{workerName}}-Job Type:{{jobType}}"
      }
     ]
    },
    {
     "title": "Rate of Jobs Handled",
     "type": "timeseries",
     "description": "Rate of jobs of jobs handled by the worker.",
     "gridPos": { "h": 6, "w": 9, "x": 8, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_client_worker_job_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, workerName, jobType)",
       "legendFormat": "Worker Name:{{workerName}}-Job Type:{{jobType}}"
      }
     ]
    },
    {
     "title": "Number Jobs in \"Buffer\"",
     "type": "timeseries",
     "description": "The difference between jobs created and jobs handled.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_client_worker_job_activated_total{cluster=~\"$cluster\", namespace=~\"$namespace\"} - zeebe_client_worker_job_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (namespace, workerName, jobType)",
       "legendFormat": "Worker Name:{{workerName}}-Job Type:{{jobType}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "In flight Requests",
     "type": "timeseries",
     "description": "Current number of request inflight per partition.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_backpressure_inflight_requests_count{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) by (partition)",
       "legendFormat": "Partition: {{partition}}"
      }
     ]
    },
    {
     "title": "Total Dropped Requests",
     "type": "timeseries",
     "description": "The rate of requests dropped due to backpressure per partition.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_dropped_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval]) ) by (partition)",
       "legendFormat": "Partition: {{partition}}"
      }
     ]
    },
    {
     "title": "Backpressure Requests Limit",
     "type": "timeseries",
     "description": "Current limit for number of inflight requests per partition.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_backpressure_requests_limit{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"} and on(namespace, partition, pod, instance) (atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"} == 3)) by (partition)",
       "legendFormat": "Partition: {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job push",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker jobs pushed",
     "type": "timeseries",
     "description": "The rate of jobs pushed from a broker to a gateway per second, where ✅ are successful pushes, and ❌ are failures",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 380 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_broker_jobs_pushed_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "✅ {{pod}}"
      },
      {
       "expr": "sum(rate(zeebe_broker_jobs_push_fail_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "❌ {{pod}}"
      }
     ]
    },
    {
     "title": "Gateway jobs pushed rate",
     "type": "timeseries",
     "description": "The amount of jobs pushed from the gateway to clients, per second, where ✅ are successful pushes, and ❌ are failures",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 380 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_gateway_job_stream_push_total{namespace=~\"$namespace\", pod=~\"$pod\", status=\"success\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "✅ {{pod}}"
      },
      {
       "expr": "sum(rate(zeebe_gateway_job_stream_push_total{namespace=~\"$namespace\", pod=~\"$pod\", status=\"failure\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "❌ {{pod}}"
      }
     ]
    },
    {
     "title": "Broker job push failed attempt",
     "type": "timeseries",
     "description": "The rate of failed job push attempts, grouped by code. Each attempt represents a direct attempt to push the job to a single client, and thus may be higher than the actual number of jobs pushed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 388 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_broker_jobs_push_fail_try_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, code)",
       "legendFormat": "❌ {{pod}} {{code}}"
      }
     ]
    },
    {
     "title": "Gateway job push failed attempt",
     "type": "timeseries",
     "description": "The rate of failed job push attempts, grouped by code. Each attempt represents a direct attempt to push the job to a single client, and thus may be higher than the actual number of jobs pushed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 388 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_gateway_job_stream_push_fail_try_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, code)",
       "legendFormat": "❌ {{pod}} {{code}}"
      }
     ]
    },
    {
     "title": "Jobs pushed by engine",
     "type": "timeseries",
     "description": "The rate of jobs activated and pushed by the engine per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 396 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\", action=\"pushed\"}[$__rate_interval])) by (namespace, partition)",
       "legendFormat": "p{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway client count",
     "type": "timeseries",
     "description": "The number of open job stream client calls on the gateway. This should be one per open StreamActivatedJobRequest calls.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 839 },
     "targets": [
      {
       "expr": "sum(zeebe_gateway_job_stream_clients{namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Gateway aggregated stream count",
     "type": "timeseries",
     "description": "The number of aggregated streams per gateway. Client streams are logically aggregated as one in a gateway if they would activate the same job with the exact same parameters.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 839 },
     "targets": [
      {
       "expr": "sum(zeebe_gateway_job_stream_streams{namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Broker job stream count",
     "type": "timeseries",
     "description": "The count of job streams registered on the broker. This should be the sum of all gateway aggregated streams.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 847 },
     "targets": [
      {
       "expr": "sum(zeebe_broker_open_job_stream_count{namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Gateway registered broker count",
     "type": "timeseries",
     "description": "The amount of known brokers (or stream servers) per gateway.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 847 },
     "targets": [
      {
       "expr": "sum(zeebe_gateway_job_stream_servers{namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful DNS requests",
     "type": "timeseries",
     "description": "Rate of successful DNS requests per second",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1446 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_dns_success_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed DNS Requests",
     "type": "timeseries",
     "description": "Rate of failed DNS requests per second",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1446 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_dns_failed_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, code)",
       "legendFormat": "{{pod}} {{code}}"
      }
     ]
    },
    {
     "title": "DNS Error",
     "type": "timeseries",
     "description": "Rate of DNS errors per second",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1446 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_dns_error_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topology Change Operations",
     "type": "timeseries",
     "description": "Number of completed and pending operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 383 },
     "targets": [
      {
       "expr": "max(zeebe_cluster_changes_operations_pending{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Pending"
      },
      {
       "expr": "max(zeebe_cluster_changes_operations_completed{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Number of Failed Operations",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 383 },
     "targets": [
      {
       "expr": "sum by (pod, operation) (zeebe_cluster_changes_operation_attempts_total{outcome=\"failed\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{operation}} on {{pod}}"
      }
     ]
    },
    {
     "title": "Operation Duration",
     "type": "heatmap",
     "description": "The time it takes to apply each operation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 391 },
     "targets": [
      {
       "expr": "sum by (le) (increase(zeebe_cluster_changes_operation_duration_bucket[$__rate_interval])) or sum by (le) (increase(zeebe_cluster_changes_operation_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Applied Operations",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 391 },
     "targets": [
      {
       "expr": "sum by (pod, operation) (zeebe_cluster_changes_operation_attempts_total{outcome=\"applied\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{operation}} on {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dynamic scaling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshot Count",
     "type": "timeseries",
     "description": "Total number of committed snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zeebe_snapshot_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap=\"true\"}[$__rate_interval])",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot for Bootstrap Size",
     "type": "timeseries",
     "description": "Size in bytes of snapshots for bootstrap on disk",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "zeebe_snapshot_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=\"1\", bootstrap=\"true\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot for Bootstrap Transfer Duration",
     "type": "heatmap",
     "description": "Approximate duration of taking a single snapshot from the processor point-of-view (without replication or committing).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_transfer_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"1\", bootstrap=\"true\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(zeebe_snapshot_transfer_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap=\"true\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Snapshot for Bootstrap Creation Duration",
     "type": "heatmap",
     "description": "Approximate duration of creating a new snapshot for bootstrap from a previously persisted snapshot.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap=\"true\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(zeebe_snapshot_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\", bootstrap=\"true\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace",
     "type": "timeseries",
     "description": "Time taken to init secondary storage schema.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 384 },
     "repeat": "namespace",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (camunda_schema_init_time_seconds_max{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}} schema init"
      }
     ]
    }
   ]
  }
 ]
}